### ISSUE TITLE
Use conda instead of virtual env

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy_benchmarks#4]
I'd prefer to use conda to pull in the dependencies (fastcache, mpmath, and eventually other optional sympy deps). Maybe we need a script that somehow gives you the option to set this instead of loading from the static config file.

BTW, mpmath is required for sympy > 0.7.6 so it probably needs to be added now to the asv conf file.

**Comment by moorepants** [comment]
I missed this but we can have multiple config files, see: https://github.com/spacetelescope/asv/issues/293#issuecomment-123120223

**Comment by bjodah** [comment]
Using conda is a good idea!
We might need to rethink the idea of Raspberry Pi 2 though since it's not x86 architecture (or just have a separate configfile using virutalenv for ARM hosts).

We could expand `./run_benchmarks.sh` to automatically give guidance on this, or just document useful asv flags and our different config files in the README.

**Comment by bjodah** [comment]
mpmath requirement addressed in #11

**Comment by moorepants** [comment]
Sounds good. We can just make multiple config files for different setups.

**Comment by moorepants** [comment]
Not so relevant, closing.
